# Generated by Django 4.0.4 on 2022-05-04 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perguntas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=3)),
                ('pergunta', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Pergunta',
                'verbose_name_plural': 'Perguntas',
            },
        ),
        migrations.CreateModel(
            name='Atividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnae', models.CharField(max_length=10)),
                ('atividade', models.CharField(max_length=500)),
                ('grau_risco', models.CharField(max_length=100)),
                ('orgao', models.CharField(max_length=50)),
                ('num_pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visa.perguntas')),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
            },
        ),
    ]
